import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.recommended,
  {
    files: ["src/**/*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setImmediate: "readonly",
        requestAnimationFrame: "readonly",
        Blob: "readonly",
        File: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Intl: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        Element: "readonly",
        React: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-unused-expressions": "warn",
      "no-constant-condition": "warn",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "warn",
      "no-unreachable": "error",
      "no-const-assign": "error",
      "no-var": "warn",
      "no-redeclare": "error",
      "no-self-assign": "error",
      "eqeqeq": ["warn", "always"],
    },
  },
];
